#!/bin/bash

function usage_abort() {
	echo "usage: cmdtodo <action> <list items>"
	echo
	echo "  action options:"
	echo "    e  -- edit lists"
	echo "    v  -- view lists"
	echo "    f [tag] -- filter lists by tag. (lines per list with <> around the 'tag' string)"
	echo "    dd -- filter lines with a ## due date #. all lists are shown here "
	echo "    new -- make a new list"
	echo "    del -- delete a list"
	echo
	echo "  list items is optional. if empty, it prompts a menu of lists to perform action on."
	echo "   if not empty, use a space separated list of names or numbers that come up on the menu "

	exit 42069
}

cd ~/cmdtodo

case $1 in
	'e') ###edit###
		shift
		./Edit.sh $@
		;;
	'v') ###view###
		shift
		./ViewLists.sh $@
		;;
	'f') ###filter###
		shift
		tag=$1
		shift
		./FilterLists.sh '<'$tag'>' $@
		;;
	'dd') ###duedates###
		./ViewLists.sh @ | grep -E '=|##.*#'
		;;
	'new') ###make new list###
		shift
		./NewList.sh $@
		;;
	'del') ###delete a list###
		echo 'feature coming soon, should be in by no later than 2024 (no promises)'
		;;
	*)
		usage_abort
		;;
esac
