#!/bin/bash

cd $CMDTODO_ROOT

case $1 in
	'-e') ###edit###
		shift
		scripts/Edit.sh $@
		;;
	'-v') ###view###
		shift
		scripts/ViewLists.sh $@
		;;
	'-f') ###filter###
		shift
		tag=$1
		shift
		scripts/FilterLists.sh '<'$tag'>' $@
		;;
	'-dd') ###duedates###
		scripts/ViewLists.sh @ | grep -E '=|##.*#'
		;;
	'-new') ###make new list###
		shift
		scripts/NewList.sh $@
		;;
	'-del') ###delete a list###
		shift
		scripts/Delete.sh $@
		;;
	*)
		cat usage.txt
		exit 1
		;;
esac
