#!/bin/bash

cd ~/cmdtodo/src

case $1 in
	'e') ###edit###
		shift
		./Edit.sh $@
		;;
	'v') ###view###
		shift
		./ViewLists.sh $@
		;;
	'f') ###filter###
		shift
		tag=$1
		shift
		./FilterLists.sh '<'$tag'>' $@
		;;
	'dd') ###duedates###
		./ViewLists.sh @ | grep -E '=|##.*#'
		;;
	'new') ###make new list###
		shift
		./NewList.sh $@
		;;
	'del') ###delete a list###
		echo 'feature coming soon, should be in by no later than 2024 (no promises)'
		;;
	*)
		cat usage.txt
		exit 1
		;;
esac
